version: "3"

services:
  dar_zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - dar_network
    volumes:
      - "/srv/dar-data/zookeeper:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  dar_kafka:
    image: docker.io/bitnami/kafka:3.2
    networks:
      - dar_network
    ports:
      - 9193:9193
    volumes:
      - "/srv/dar-data/kafka:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=dar_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9193
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://dar_kafka:9092,EXTERNAL://localhost:9193
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LINGER_MS=20
      - KAFKA_CFG_BATCH_SIZE=65536
      - KAFKA_CFG_LOG_RETENTION_HOURS=-1
      - KAFKA_CFG_LOG_RETENTION_BYTES=-1
    depends_on:
      - dar_zookeeper
  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - dar_network
    ports:
      - "8081:8081"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=dar_kafka:9092
      - SERVER_PORT=8081
networks:
  dar_network:
